#!/usr/bin/env node

import fs from 'fs';
import path from 'path';

const products = [
  { id: 'pan-4-granos', nombre: 'Pan 4 Granos', desc: 'Elaborado con una combinación de harina de trigo, trigo entero molido, agua, granos enteros de linaza, avena, ajonjolí, girasol, sal, levadura y conservantes. Es 100% libre de azúcares y grasas añadidas.', seo: 'Pan integral de 4 granos con linaza, avena y ajonjolí. 100% libre de azúcares y grasas. Certificado Kosher Pat Israel. Ideal para dietas balanceadas.', kw: ['pan integral', 'pan 4 granos', 'pan sin azúcar', 'pan kosher', 'panadería New York Caracas'], cat1: 'supermarket', cat2: 'panes', img: 'pan-4-granos', specs: { peso: '500 g', codigo_barras: '7591348001031', tiempoVida: '15 días', temperatura: 'ambiente' }, certs: ['Kosher Pat Israel'], dest: true },
  { id: 'pan-7-cereales', nombre: 'Pan 7 Cereales', desc: 'Una mezcla artesanal de centeno, trigo, maíz, avena, quinoa, cebada y ajonjolí. Fuente de carbohidratos complejos, cero colesterol, bajo índice glicémico, cero grasas trans, rico en fibras solubles e insolubles.', seo: 'Pan integral de 7 cereales con centeno, trigo, maíz, avena, quinoa, cebada y ajonjolí. Bajo índice glucémico, rico en fibra. Kosher Pat Israel.', kw: ['pan 7 cereales', 'pan integral multicereales', 'pan bajo índice glucémico', 'pan sin colesterol', 'panadería artesanal Caracas'], cat1: 'supermarket', cat2: 'panes', img: 'pan-7-cereales', specs: { peso: '600 g', tiempoVida: '15 días', temperatura: 'ambiente' }, certs: ['Kosher Pat Israel'] },
  { id: 'pan-blanco-especial', nombre: 'Pan Blanco Especial', desc: 'Pan elaborado con harina de trigo refinada de alta calidad, proporcionando una miga ligera y esponjosa. Excelente opción para quienes requieren una fuente rápida de energía.', seo: 'Pan blanco especial de sandwich esponjoso de alta calidad. Miga ligera perfecta para sándwiches. Panadería premium New York.', kw: ['pan blanco', 'pan de sandwich', 'pan esponjoso', 'panadería New York', 'pan premium'], cat1: 'supermarket', cat2: 'panes', img: 'pan-blanco-especial', specs: { peso: '600 g', tiempoVida: '15 días', temperatura: 'ambiente' }, certs: ['Kosher Pat Israel'] },
  { id: 'pan-uvas-pasas-miel-canela', nombre: 'Pan Uvas Pasas, Miel y Canela', desc: 'Pan integral que incorpora pasas, miel y canela. La miel actúa como prebiótico favoreciendo la flora intestinal, mientras que la canela ayuda a regular los niveles de azúcar en la sangre.', seo: 'Pan integral dulce con uvas pasas, miel y canela. Prebiótico natural. Regula niveles de azúcar. Panadería premium Caracas.', kw: ['pan integral', 'pan con pasas', 'pan con miel y canela', 'pan prebiótico', 'panadería New York'], cat1: 'supermarket', cat2: 'panes', img: 'pan-uvas-pasas-miel-canela', specs: { peso: '600 g', tiempoVida: '15 días', temperatura: 'ambiente' }, certs: ['Kosher Pat Israel'] },
  { id: 'magdalenas', nombre: 'Magdalenas', desc: 'Magdalenas inspiradas en la receta clásica del ponqué español, con una miga esponjosa y un delicado aroma a limón. Individualmente empacadas, ideales para la lonchera escolar, la oficina o la playa.', seo: 'Magdalenas artesanales de limón, ponquecitos esponjosos. Empacadas individualmente para lonchera. Panadería premium New York Caracas.', kw: ['magdalenas', 'ponquecitos', 'ponqué de limón', 'repostería artesanal', 'panadería premium'], cat1: 'supermarket', cat2: 'reposteria', img: 'magdalenas', specs: { peso: '10x45g', tiempoVida: '3 meses', temperatura: 'ambiente' }, certs: ['Producto Kosher'] },
  { id: 'pan-pumpernickel', nombre: 'Pan Pumpernickel', desc: 'Elaborado exclusivamente con granos enteros de centeno 100% orgánicos y con masa madre natural. Excelente opción para regular el metabolismo y mejorar la salud digestiva. Su bajo índice glucémico lo hace ideal para personas con resistencia a la insulina o diabetes.', seo: 'Pan Pumpernickel 100% centeno orgánico con masa madre. Bajo índice glucémico. Ideal para diabetes. Panadería premium Caracas.', kw: ['pan pumpernickel', 'pan de centeno', 'pan orgánico', 'pan bajo índice glucémico', 'panadería premium'], cat1: 'supermarket', cat2: 'panes', img: 'pan-pumpernickel', specs: { peso: '210 g', tiempoVida: '3 meses', temperatura: 'ambiente' }, certs: ['Kosher Pat Israel'] },
  { id: 'pan-molido-especial', nombre: 'Pan Molido Especial', desc: 'A diferencia de otros panes rallados que provienen del reciclaje de pan sobrante, nuestro producto es elaborado específicamente para ser molido, garantizando frescura, uniformidad y una textura ideal para rebozados, gratinados y mezclas culinarias.', seo: 'Pan rallado artesanal molido especialmente. Fresco y uniforme. Ideal para rebozados y gratinados. Panadería premium New York.', kw: ['pan rallado', 'pan molido', 'rebozos', 'gratinados', 'panadería premium'], cat1: 'supermarket', cat2: 'reposteria', img: 'pan-molido-especial', specs: { peso: '300 g', tiempoVida: '12 meses', temperatura: 'ambiente' }, certs: ['Kosher Pat Israel'] },
  { id: 'baguettes-precocida-comercial', nombre: 'Baguettes Precocida Congelada - Comercial', desc: 'Baguettes precocidas congeladas que combinan la tradición artesanal con la comodidad moderna. Elaboradas con masa madre, ofrecen una corteza crujiente y una miga aireada. Disponibles en tres tamaños: 32 cm, 21 cm y 11 cm.', seo: 'Baguettes precocidas congeladas artesanales. Empaque comercial retail. Tres tamaños (32/21/11 cm). Panadería premium New York.', kw: ['baguettes', 'baguette congelada', 'pan francés', 'precocido', 'panadería New York'], cat1: 'supermarket', cat2: 'panes', img: 'baguettes-precocida-comercial', specs: { peso: '225 g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Kosher Pat Israel'] },
  { id: 'baguettes-precocida-foodservice', nombre: 'Baguettes Precocida Congelada - Foodservice', desc: 'Baguettes precocidas congeladas para servicio profesional. Elaboradas con masa madre, ofrecen corteza crujiente y miga aireada. Formato bulk/bolsa sin empaque especial.', seo: 'Baguettes precocidas congeladas formato foodservice. Bulk. Restaurantes y catering. Panadería premium Caracas.', kw: ['baguettes foodservice', 'baguette congelada restaurante', 'pan francés catering', 'bulk', 'panadería profesional'], cat1: 'foodservice', cat2: 'panes', img: 'baguettes-precocida-foodservice', specs: { peso: '225 g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Kosher Pat Israel'] },
  { id: 'pizza-margarita-premium', nombre: 'Pizza Margarita Premium', desc: 'Pizza artesanal precocida premium con masa de fermentación lenta. Ingredientes de alta calidad con harina de trigo seleccionada y fermentación natural. Sabor auténtico con digestión más ligera.', seo: 'Pizza Margarita Premium artesanal congelada. Fermentación lenta. Ingredientes seleccionados. Panadería premium New York.', kw: ['pizza margarita', 'pizza congelada', 'pizza premium', 'pizza artesanal', 'panadería New York'], cat1: 'supermarket', cat2: 'pizza', img: 'pizza-margarita-premium', specs: { peso: '2 Uds - 550g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Producto Premium'], dest: true },
  { id: 'pizza-margarita-clasica', nombre: 'Pizza Margarita Clásica', desc: 'Pizza margarita estándar, precocida y congelada. Masa artesanal con fermentación natural. Auténtica receta italiana: tomate, queso y albahaca.', seo: 'Pizza Margarita Clásica congelada. Receta italiana auténtica. Masa fermentada natural. Panadería premium Caracas.', kw: ['pizza margarita', 'pizza italiana', 'pizza congelada', 'pizza tradicional', 'panadería premium'], cat1: 'supermarket', cat2: 'pizza', img: 'pizza-margarita-premium', specs: { peso: '2 Uds - 550g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Producto Premium'] },
  { id: 'pizza-americana', nombre: 'Pizza Americana', desc: 'Pizza con los sabores clásicos americanos, precocida y congelada. Masa artesanal de fermentación lenta con ingredientes seleccionados.', seo: 'Pizza Americana congelada. Sabores americanos. Masa artesanal fermentada. Panadería premium New York Caracas.', kw: ['pizza americana', 'pizza congelada', 'pizza artesanal', 'pizza premium', 'panadería New York'], cat1: 'supermarket', cat2: 'pizza', img: 'pizza-margarita-premium', specs: { peso: '2 Uds - 650g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Producto Premium'] },
  { id: 'torta-queso-new-york-fresa', nombre: 'Torta de Queso New York - Fresa', desc: 'Cheesecake estilo New York que combina la suavidad de un queso crema premium con una base delicada. Cubierta con mermelada de fresa artesanal. Perfecto balance entre dulzura y textura cremosa en cada bocado.', seo: 'Cheesecake New York Fresa congelada. Queso crema premium. Mermelada artesanal. Postre gourmet Caracas.', kw: ['cheesecake', 'torta de queso', 'cheesecake fresa', 'postre premium', 'repostería Caracas'], cat1: 'supermarket', cat2: 'reposteria', img: 'torta-queso-new-york-fresa', specs: { peso: '700g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Producto Premium'], dest: true },
  { id: 'torta-queso-new-york-chocolate', nombre: 'Torta de Queso New York - Chocolate', desc: 'Cheesecake estilo New York con queso crema premium y cobertura de chocolate intenso. Equilibrio perfecto entre dulzura y textura cremosa, elegante presentación.', seo: 'Cheesecake New York Chocolate. Cobertura chocolate intenso. Queso crema premium. Postre gourmet premium.', kw: ['cheesecake', 'torta de queso', 'cheesecake chocolate', 'postre premium', 'repostería gourmet'], cat1: 'supermarket', cat2: 'reposteria', img: 'torta-queso-new-york-fresa', specs: { peso: '700g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Producto Premium'], dest: true },
  { id: 'torta-queso-new-york-comercial-fresa', nombre: 'Torta de Queso New York Comercial - Fresa', desc: 'Cheesecake estilo New York grande para restaurantes y cafeterías. Hecha con queso crema de la más alta calidad sobre una base de galleta artesanal especiada. Textura suave, densa y equilibrada. Cubierta con mermelada de fresa artesanal.', seo: 'Cheesecake New York Comercial 1500g Fresa. Hostelería. Restaurantes. Panadería premium Caracas.', kw: ['cheesecake comercial', 'torta grande', 'restaurante', 'hostelería', 'repostería professional'], cat1: 'foodservice', cat2: 'reposteria', img: 'torta-queso-comercial', specs: { peso: '1500g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Producto Premium'] },
  { id: 'torta-queso-new-york-comercial-chocolate', nombre: 'Torta de Queso New York Comercial - Chocolate', desc: 'Cheesecake estilo New York grande para hostelería. Queso crema premium sobre base de galleta especiada. Cubierta con chocolate premium. Ideal para restaurantes, eventos y vitrinas de pastelería.', seo: 'Cheesecake New York Comercial 1500g Chocolate. Hostelería. Restaurantes catering. Panadería premium.', kw: ['cheesecake comercial', 'torta chocolate', 'restaurante', 'hostelería', 'repostería profesional'], cat1: 'foodservice', cat2: 'reposteria', img: 'torta-queso-comercial', specs: { peso: '1500g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Producto Premium'] },
  { id: 'torta-queso-new-york-comercial-plain', nombre: 'Torta de Queso New York Comercial - Plain', desc: 'Cheesecake estilo New York grande sin cobertura, ideal para clientes que deseen personalizar la base. Queso crema premium sobre base de galleta artesanal especiada. Formato perfecto para restaurantes con coberturas personalizadas.', seo: 'Cheesecake New York Comercial 1500g Plain sin cobertura. Hostelería personalizada. Panadería premium Caracas.', kw: ['cheesecake plain', 'cheesecake sin cobertura', 'restaurante', 'hostelería', 'repostería profesional'], cat1: 'foodservice', cat2: 'reposteria', img: 'torta-queso-comercial', specs: { peso: '1300g', tiempoVida: '9 meses', temperatura: '-18°C' }, certs: ['Producto Premium'] },
  { id: 'pan-hamburguesa-new-york', nombre: 'Pan de Hamburguesa - New York', desc: 'Pan de hamburguesa con textura esponjosa de miga suave. Resistente a rellenos y salsas sin perder su forma. Versión clásica New York con topping de ajonjolí que realza su sabor.', seo: 'Pan de hamburguesa New York esponjoso con ajonjolí. Miga suave. Resistente salsas. Panadería premium Caracas.', kw: ['pan hamburguesa', 'pan esponjoso', 'pan ajonjolí', 'panadería New York', 'pan artesanal'], cat1: 'supermarket', cat2: 'panes', img: 'pan-hamburguesa-new-york', specs: {}, certs: ['Producto Kosher'] },
  { id: 'pan-hamburguesa-brioche', nombre: 'Pan de Hamburguesa - Brioche', desc: 'Pan de hamburguesa brioche con miga esponjosa y suave. Versión brioche sin topping. La miga tiene memoria que garantiza una llamativa presentación. Resistente a rellenos y salsas.', seo: 'Pan de hamburguesa Brioche esponjoso. Miga con memoria. Sin topping. Panadería premium New York.', kw: ['pan brioche', 'pan hamburguesa', 'pan esponjoso', 'panadería premium', 'pan artesanal'], cat1: 'supermarket', cat2: 'panes', img: 'pan-hamburguesa-new-york', specs: {}, certs: ['Producto Kosher'] },
  { id: 'baguettes-demi-mini', nombre: 'Baguettes Demi/Mini', desc: 'Baguettes con corteza crujiente e interior aireado. Disponibles en tres tamaños: 32 cm, 21 cm y 11 cm. Versión plain ideal para pepitos y sándwiches, versión con topping (orégano o ajonjolí) para más sabor.', seo: 'Baguettes Mini Demi artesanales crujientes. Tres tamaños (32/21/11 cm). Plain o con topping. Panadería New York.', kw: ['baguettes', 'baguette mini', 'demi baguette', 'pan francés', 'panadería artesanal'], cat1: 'supermarket', cat2: 'panes', img: 'baguettes-demi-mini', specs: {}, certs: ['Kosher Pat Israel'] },
  { id: 'croissants', nombre: 'Croissants y Petit Croissants', desc: 'Croissants de técnica, tiempo y mantequilla 100% de calidad superior. Corteza dorada que cruje al primer contacto e interior alveolado, ligero y profundo en sabor. Sin conservantes. Disponibles en tamaño estándar (80g) y petit (25g).', seo: 'Croissants artesanales hojaldre francés 100% mantequilla. Sin conservantes. Dos tamaños. Panadería premium Caracas.', kw: ['croissants', 'hojaldre', 'pan francés', 'mantequilla', 'panadería artesanal'], cat1: 'supermarket', cat2: 'reposteria', img: 'croissants', specs: { peso: '80g / 25g' }, certs: [] },
  { id: 'bagels-new-york-plain', nombre: 'Bagels estilo New York - Plain', desc: 'Auténticos bagels estilo New York elaborados bajo el proceso genuino de escaldado y horneado. Miga densa y masticable, sabor clásico pero lleno de sabor. Versión plain sin toppings.', seo: 'Bagels New York Plain auténticos escaldados. Miga densa masticable. Panadería premium Caracas.', kw: ['bagels', 'bagel new york', 'pan escaldado', 'miga densa', 'panadería artesanal'], cat1: 'supermarket', cat2: 'especialidades', img: 'bagels-new-york-plain', specs: { peso: '95g' }, certs: ['Kosher Pat Israel'] },
  { id: 'bagels-new-york-ajonjoli', nombre: 'Bagels estilo New York - Ajonjolí', desc: 'Bagels estilo New York con cobertura de ajonjolí. Escaldados y horneados auténticamente. Crunch y toque tostado sutil. Miga densa y masticable.', seo: 'Bagels New York Ajonjolí con topping. Escaldados auténticos. Miga densa. Panadería premium New York.', kw: ['bagels', 'bagel ajonjolí', 'pan escaldado', 'sesame bagel', 'panadería artesanal'], cat1: 'supermarket', cat2: 'especialidades', img: 'bagels-new-york-plain', specs: { peso: '95g' }, certs: ['Kosher Pat Israel'] },
  { id: 'bagels-new-york-everything', nombre: 'Bagels estilo New York - Everything', desc: 'Bagels estilo New York con mezcla aromática everything: sésamo, amapola, ajo y cebolla deshidratada. Diseñados para escalar tu menú al siguiente nivel. Auténtica receta escaldada y horneada.', seo: 'Bagels New York Everything múltiples toppings. Sésamo amapola ajo cebolla. Panadería premium Caracas.', kw: ['bagels', 'bagel everything', 'sésamo amapola', 'pan escaldado', 'panadería artesanal'], cat1: 'supermarket', cat2: 'especialidades', img: 'bagels-new-york-plain', specs: { peso: '95g' }, certs: ['Kosher Pat Israel'], dest: true },
  { id: 'pan-1700', nombre: 'Pan 1700', desc: 'El Pan 1700 es una versión ampliada del Pan Blanco Especial, manteniendo su suavidad y equilibrio perfecto entre miga esponjosa y corteza delicada. Ideal para sector de restauración, eventos o familias. Rinde 40 rebanadas. Disponible en versión brioche estilo Hokkaido.', seo: 'Pan 1700 grande blanco esponjoso. Hostelería eventos familias. 40 rebanadas. Panadería premium New York.', kw: ['pan 1700', 'pan grande', 'pan blanco', 'panadería profesional', 'pan hostelería'], cat1: 'foodservice', cat2: 'panes', img: 'pan-1700', specs: {}, certs: ['Kosher Pat Israel'] },
];

const output = '/Users/eugenio/repos/new-york-venezuela/web/src/content/productos';

products.forEach(p => {
  const md = `---
title: "${p.nombre}"
id: "${p.id}"
descripcion_seo: "${p.seo}"
palabras_clave: ${JSON.stringify(p.kw)}
categoria_primaria: "${p.cat1}"
categoria_secundaria: "${p.cat2}"
imagen: "${p.img}"
imagen_alt: "${p.nombre} - panadería premium New York, Caracas"
destacado: ${p.dest ? 'true' : 'false'}
og_type: "product"
---

# ${p.nombre}

## Descripción

${p.desc}

## Certificaciones

${p.certs.length > 0 ? p.certs.map(c => `- **${c}**`).join('\n') : 'Producto estándar de panadería premium.'}

## Especificaciones Técnicas

${Object.keys(p.specs).length > 0 ? `| Campo | Valor |
|-------|-------|
${Object.entries(p.specs).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}` : 'Consulte con nuestro equipo de ventas para especificaciones detalladas.'}

## Usos Recomendados

- Consumo directo o para preparaciones culinarias
- Disponible en puntos de venta autorizados
- Para consultas de distribución, contacte a nuestro equipo comercial
`;

  fs.writeFileSync(path.join(output, `${p.id}.md`), md);
});

console.log(`✓ Generated ${products.length} markdown content files`);
